@echo off
cd /d "D:\??\3?? 1??\AI????? ? ??\main_project_final"
echo [1/6] ?? ?? ?? (P0+P1, ?? 500?)...
apps\search-api\.venv\Scripts\python.exe -m pipelines.collect_cases --priority P0,P1 --limit 500 --scope criminal >> pipeline_criminal.log 2>&1
echo [2/6] normalize...
apps\search-api\.venv\Scripts\python.exe -m pipelines.normalize >> pipeline_criminal.log 2>&1
echo [3/6] split...
apps\search-api\.venv\Scripts\python.exe -m pipelines.split >> pipeline_criminal.log 2>&1
echo [4/6] extract...
apps\search-api\.venv\Scripts\python.exe -m pipelines.extract >> pipeline_criminal.log 2>&1
echo [5/6] structure...
apps\search-api\.venv\Scripts\python.exe -m pipelines.structure >> pipeline_criminal.log 2>&1
echo [6/6] validate...
apps\search-api\.venv\Scripts\python.exe -m pipelines.validate >> pipeline_criminal.log 2>&1
echo [EMBED] embed...
apps\search-api\.venv\Scripts\python.exe -m pipelines.embed >> pipeline_criminal.log 2>&1
echo Pipeline complete.
